top:
  options:
    x: 5
    y: 5
    padding: 5
    font_desc: Iosevka Medium 13
    opacity: 70
  bars:
    - name: CPU
      type: cpu
      width: 100
      height: 22
      # Customize the high CPU usage color and threshold
      danger_color: "#ff2222"
      danger_threshold: 40

    - name: battery
      type: shell
      # background_color: "#222"
      # Customize the opacity, for kicks
      width: 70
      height: 22
      command: >
        acpi -b | cut -d',' -f2 | cut -c2-
      update_interval: 5

    - name: temperature
      type: shell
      # background_color: "#222"
      # Customize the opacity, for kicks
      width: 70
      height: 22
      command: >
        echo "$(acpi -t | cut -d' ' -f4)°C"
      update_interval: 5

    - name: xtitle
      type: shell
      # Customize the opacity, for kicks
      opacity: 80
      width: 1100
      height: 22
      # http://stackoverflow.com/questions/12873682/short-way-to-escape-html-in-bash
      command: >
        xtitle | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g'
      update_interval: 0.1

bottom:
  options:
    x: 5
    y: 741
    font_desc: Iosevka Medium 13
    opacity: 70
  bars:
    - name: date
      type: shell
      width: 96
      height: 22
      command: date +"%H:%M:%S"
      update_interval: 1

    - name: mpd
      type: mpd
      # Customize the opacity, for kicks
      opacity: 80
      width: 1254
      height: 22
      total_width: 191
      elapsed_char: ─
      update_interval: 0.5
